- name: copr
  become: yes
  community.general.copr:
    name: "{{item}}"
  loop:
    - agriffis/neovim-nightly
    - alebastr/sway-extras
    - atim/bandwhich
    - atim/bottom
    - atim/lazydocker
    - atim/lazygit
    - fuhrmann/ctop
    - lehrenfried/fzy
    - eddsalkield/swaylock-effects

- name: gh repo
  become: yes
  command:
    cmd: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/gh-cli.repo
