# [[shades]]
# name = "vibrance"
# default = true  # shader to use during times when there is no other shader scheduled

[[shaders]]
name = "blue-light-filter"
start_time = 19:00:00
end_time = 06:00:00
[shaders.config]
temperature = 3600
strength = 1
