- name: Keyd
  become: true
  copy:
    dest: /etc/keyd/default.conf
    src: ~/dot/ansible/roles/system/files/keyd.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable Keyd Daemon
  become: true
  ansible.builtin.systemd:
    name: keyd
    enabled: yes
    state: started

- name: Powersave udev rule
  become: true
  copy:
    dest: /etc/udev/rules.d/powersave.rules
    src: ~/dot/ansible/roles/system/files/powersave.rules
    owner: root
    group: root
    mode: "0644"
# - name: Touchpad
#   become: true
#   copy:
#     dest: /etc/X11/xorg.conf.d/30-touchpad.conf
#     src: ~/dot/ansible/roles/system/files/touchpad.conf
#     owner: root
#     group: root
#     mode: "0644"
#
# - name: prefer libinput over synaptics
#   become: true
#   file:
#     src: /usr/share/X11/xorg.conf.d/40-libinput.conf
#     dest: /etc/X11/xorg.conf.d/40-libinput.conf
#     state: link

# - name: Install Sway Autotiling
#   pip:
#     name:
#       - autotiling
#       - flashfocus
#
# - name: Disable sudo systemctl disable NetworkManager-wait-online.service
#   become: true
#   ansible.builtin.systemd:
#     name: NetworkManager-wait-online.service
#     state: stopped
#     enabled: no
