#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
#colorscheme = "nord"
#colorscheme = "onedark"
  colorscheme = "palenight"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "bar"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  enable_os_fileformat_icon = true
  statusline_unicode_symbols = true
  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = false
  autocomplete_method = "coc"

[[layers]] 
  name = 'lsp'
  filetypes = [
    'typescript',
    'javascript',
    'css',
    'vue',
    'html'
  ]

[[layers]]
  name = "sudo"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = "colorscheme"

[[custom_plugins]]
  name = "dracula/vim"
  merged = 0

[[custom_plugins]]
  name = "dylanaraps/wal.vim"
  merged = 0

[[custom_plugins]]
  name = "romainl/Apprentice"
  merged = 0

[[custom_plugins]]
  name = "kovetskiy/sxhkd-vim"
  merged = 0

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#fish"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
name = "VersionControl"

[[layers]]
  name = "lang#typescript"

[[layers]]
name = "git"
